services:
  rmd-client:
    build: .
    container_name: rmd-client
    env_file:
      - .env
    environment:
      - RMCLUSTER_CLIENT_DATA_DIR=/var/app/data
    volumes:
      - rmd-client-data:/var/app/data
    restart: unless-stopped
    command: ["-tracker", "${TRACKER_IP}"]

volumes:
  rmd-client-data:
